FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY classifier_side/ ./classifier_side/
COPY __init__.py .

CMD ["uvicorn", "classifier_side.serviceAPI:app", "--host", "0.0.0.0", "--port", "8000"]
