FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ../data/health_generated.csv ./app/data/
COPY model_side/ ./model_side/
COPY __init__.py .

CMD ["uvicorn", "model_side.modelAPI:app", "--host", "0.0.0.0", "--port", "8001"]
